apiVersion: 1

datasources:
  - name: "Loki"
    type: "loki"
    access: "proxy"
    url: "http://loki:3100"
    basicAuth: false
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceType: "tempo"
          datasourceUid: "P214B5B846CF3925F"  # ID manual de Tempo
          matcherRegex: "(trace_id=\\w+)"
          name: "trace_id"
          url: ""
    readOnly: false

  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://prometheus:9090"
    basicAuth: false
    isDefault: false
    jsonData: {}
    readOnly: false

  - name: "Tempo"
    type: "tempo"
    access: "proxy"
    url: "http://tempo:3100"
    basicAuth: false
    isDefault: false
    jsonData:      
      lokiSearch:
        datasourceUid: "P8E80F9AEF21F6940"
      nodeGraph:
        enabled: true
      search:
        hide: false
      serviceMap:
        datasourceUid: "PBFA97CFB590B2093"  # ID manual de Prometheus
      tracesToLogsV2:
        customQuery: true
        datasourceUid: "P8E80F9AEF21F6940"  # ID manual de Loki
        query: '{env="development"} |= `$${__span.traceId}`'
        tags:
          - key: "trace_id"
            value: "trace_id"
    readOnly: false
